// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZU_9EFW4XqXDcs8zumin1mHyxxFoN_hM',
    appId: '1:767609644350:web:2afbdb4f86a515d36b386f',
    messagingSenderId: '767609644350',
    projectId: 'expenses-tracker-3fd49',
    authDomain: 'expenses-tracker-3fd49.firebaseapp.com',
    storageBucket: 'expenses-tracker-3fd49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyx4FtVRG5X_kCY_SIBiGmmK-L4XVQOBg',
    appId: '1:767609644350:android:a6e54e25d1f561406b386f',
    messagingSenderId: '767609644350',
    projectId: 'expenses-tracker-3fd49',
    storageBucket: 'expenses-tracker-3fd49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgcVRljYfr3qLGTS1-cAc4tlzjcF8-5v0',
    appId: '1:767609644350:ios:cd78f824f47895476b386f',
    messagingSenderId: '767609644350',
    projectId: 'expenses-tracker-3fd49',
    storageBucket: 'expenses-tracker-3fd49.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgcVRljYfr3qLGTS1-cAc4tlzjcF8-5v0',
    appId: '1:767609644350:ios:cd78f824f47895476b386f',
    messagingSenderId: '767609644350',
    projectId: 'expenses-tracker-3fd49',
    storageBucket: 'expenses-tracker-3fd49.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZU_9EFW4XqXDcs8zumin1mHyxxFoN_hM',
    appId: '1:767609644350:web:832713af55bf525e6b386f',
    messagingSenderId: '767609644350',
    projectId: 'expenses-tracker-3fd49',
    authDomain: 'expenses-tracker-3fd49.firebaseapp.com',
    storageBucket: 'expenses-tracker-3fd49.firebasestorage.app',
  );
}
